config/routes.rb
KursachPoBibd::Application.routes.draw do
  resources :stores
  resources :suppliers
  resources :products
  resources :supplies, :except => [:destroy, :update, :edit, :show]
  resources :orders, :except => [:destroy, :update, :edit, :show]

  root :to => "welcome#index"

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :name, :address, :description

  has_many :orders, :dependent => :nullify

  validates_presence_of :name
end

app/controllers/stores_controller.rb
# -*- coding: utf-8 -*-
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(params[:store])
    if @store.save
      flash[:notice] = "Магазин создан"
      redirect_to @store
    else
      render :action => 'new'
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update_attributes(params[:store])
      flash[:notice] = "Магазин обновлён"
      redirect_to @store
    else
      render :action => 'edit'
    end
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    flash[:notice] = "Магазин удалён"
    redirect_to stores_url
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= f.inputs :name, :address, :description %>
<%= f.buttons %>

app/views/stores/edit.html.erb
<% title "Редактировать магазин" %>

<%= semantic_form_for @store do |f| %>
  <%= render 'form', :f => f  %>
<% end %>

app/views/stores/index.html.erb
<% title "Магизины" %>
<p>Список магазинов, в которые осуществляется поставка товара со склада.</p>

<table class="table">
  <tr>
    <th>Название</th>
    <th>Адрес</th>
    <th>Примечание</th>
    <th></th>
  </tr>
  <% for store in @stores %>
    <tr>
      <td><%= link_to store.name, store %></td>
      <td><%= store.address %></td>
      <td><%= store.description %></td>
      <td>
        <%= link_to "Редактировать", edit_store_path(store) %><br />
        <%= link_to "Удалить", store, :confirm => 'Вы уверены?', :method => :delete %>
      </td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Добавить магазин", new_store_path %></p>

app/views/stores/new.html.erb
<% title "Новый магазин" %>

<%= semantic_form_for @store do |f| %>
  <%= render 'form', :f => f  %>
<% end %>

app/views/stores/show.html.erb
<% title "Магазин '#{@store.name}'" %>

<p><%= @store.address %></p>
<p><%= @store.description %></p>

<p>
  <%= link_to "Редактировать", edit_store_path(@store) %> |
  <%= link_to "Удалить магазин", @store, :confirm => 'Вы уверены?', :method => :delete %> |
  <%= link_to "К списку всех магазинов", stores_path %>
</p>