config/routes.rb
KursachPoBibd::Application.routes.draw do
  resources :stores
  resources :suppliers
  resources :products
  resources :supplies, :except => [:destroy, :update, :edit, :show]
  resources :orders, :except => [:destroy, :update, :edit, :show]

  root :to => "welcome#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ильюкевич Виктор, гр. 700621с</title>
    <%= stylesheet_link_tag "application" %>
    <%= formtastic_stylesheet_link_tag %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <ul>
        <li><b><%= link_to 'Состояние склада', root_path %></b></li>
        <li><%= link_to 'Магазины', stores_path %></li>
        <li><%= link_to 'Поставщики товара', suppliers_path %></li>
        <li><%= link_to 'Товары, с которыми ведётся работа', products_path %></li>
      </ul>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>